apiVersion: v1
kind: Service
metadata:
  name: ingress-svc
  labels:
    app: ingress-svc
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 443
    name: https
    protocol: TCP
  selector:
    app: web
  type: ClusterIP